### ISSUE TITLE
Restrict resizable directions

### ISSUE THREAD

**Issue by ngotchac** [patbuergin/angular-widget-grid#1]
Hi,
First, great work, it looks really nice!

It could be nice to add the ability to restrict the resizability (is that a word?) of a widget to specific directions. For example, I want to be able to resize a widget only vertically (North & South).

**Comment by ngotchac** [comment]
Waow great, thanks!!

**Comment by patbuergin** [comment]
Hi there, thanks for your feedback! I've added an optional parameter and you can now restrict the directions like that: `wg-resizable="{ directions: ['NW', 'NE', 'E', 'SW'] }"`. I'll update the README in the upcoming days.
