### ISSUE TITLE
Fixed tile size

### ISSUE THREAD

**Issue by Marchrius** [patbuergin/angular-widget-grid#12]
There is a way to implement a fixed tiled layout?

**Comment by patbuergin** [comment]
What exactly are you trying to achieve?

The layout is tiled by default, and it could be considered "fixed" if you make it non-editable. Are you referring to fixed as in fixed pixel width/height per item?

**Comment by Marchrius** [comment]
Sorry, I'm too generic.

What I mean is: at the moment I can place a tile in a specific position and a specific dimension. If I add a new tile it will be placed in the biggest available space in the grid. What I'm looking for is to place a new element in the grid with a fixed width and height and the top/left calculated automatically by the directive. There is a way to accomplish this?

**Comment by patbuergin** [comment]
If the fixed width/height is constant, you can easily implement this behavior by changing [this method](https://github.com/patbuergin/angular-widget-grid/blob/d4884d442b61d89354ce590c3cdc2eece0cf5b10/src/js/factories/GridRendering.js#L160-172) to not return the largest empty area, but the most appropriate location that would fit the new element (or null).

**Comment by Marchrius** [comment]
Yes, you are right. I might check this function before asking.

I'll try to mod the function or add a total new logic to implement it as new feature.

In the meantime I've modded the lib to use a double binding and parametrize the resizable/movable attributes per item. #13

**Comment by patbuergin** [comment]
Good stuff! I'll process the PR on the weekend.
