### ISSUE TITLE
Save/Load Layout

### ISSUE THREAD

**Issue by pablodiazpro** [patbuergin/angular-widget-grid#4]
Any recommendation on how to add 'save/load current layout' functionality?

**Comment by patbuergin** [comment]
The layout is defined by two things:
1. The dimensions of the grid (`<wg-grid columns="..." rows="..."`)
2. The positions of individual widgets (`<wg-widget position="..."`)

By persisting/re-applying both, you can easily implement a 'save/load current layout' functionality.

In my own use case, I populate the grid via `ng-repeat`, and persist the underlying collection as a whole.

**Comment by pablodiazpro** [comment]
Fantastic, thanks for quick response.
The idea of using a snapping grid to set up the layout is fantastic.
